# Numpy(수치해석용 패키지)

In [15]:
import numpy as np

### 배열 생성

In [16]:
data = np.array([1, 2, 3, 4])

In [17]:
data, type(data)

(array([1, 2, 3, 4]), numpy.ndarray)

In [18]:
data_2 = np.zeros(5)
data_2

array([0., 0., 0., 0., 0.])

In [19]:
data_3 = np.ones([3, 5])
data_3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
data_4 = np.arange(0, 10, 1) #기억 for i in "range()"
data_4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
data_5 = np.linspace(1, 10, 5) # (시작, 끝(포함), 개수)
data_5

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [35]:
data_log = np.logspace(1, 10, 3) # (시작, 끝(포함), 개수)
data_log

array([1.00000000e+01, 3.16227766e+05, 1.00000000e+10])

In [29]:
data_6 = np.random.randint(1, 10, size=(2, 10))
data_6

array([[3, 4, 2, 9, 6, 2, 8, 7, 5, 9],
       [7, 6, 7, 3, 3, 3, 9, 3, 3, 9]])

- data_6과 동일한 size의 0 array를 만들고 싶다면?

In [36]:
data_zero = np.zeros_like(data_6)
data_zero

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [37]:
data_one = np.ones_like(data_6)
data_one

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

### 배열 파악

In [38]:
data_one.ndim # 배열의 차원

2

In [40]:
data_one.shape #배열의 shape

(2, 10)

In [41]:
data_one.dtype #배열의 데이터의 type

dtype('int32')

In [51]:
#리스트와 비교
data_list = [1, 2.0, 'hello'] 

data_array = np.array([1, 2.0, 'hello']) 
data_array

array(['1', '2.0', 'hello'], dtype='<U32')

In [52]:
data_array.dtype

dtype('<U32')

In [53]:
data_array[0]

'1'

In [57]:
data_array2 = np.array([1, 2, 3])

data_array2.astype('f') #배열의 데이터의 형변환

array([1., 2., 3.], dtype=float32)

In [60]:
data_array2.astype('O') #주의 문자열 : 'O(알파벳)'

array([1, 2, 3], dtype=object)

### Numpy의 강점

- 1개의 데이터 : Vector = 1차원 배열
- 여러개의 데이터 : Matrix = 2차원 배열

1. 벡터화 연산이 가능하다.
2. 변환이 쉽다.
3. 조건식으로 데이터 지정하기가 쉽다.
4. 계산이 빠르다.

In [63]:
#리스트와 비교
a = [1, 2, 3]
c = a * 3 # +은 불가
c

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [65]:
x = np.array(a)
y, z = x + 3, x * 3
y, z

(array([4, 5, 6]), array([3, 6, 9]))

In [72]:
data1 = np.array([1, 2, 3, 4])
data2 = np.array([4, 1, 0, 0])

data1 + data2, data1*data2

(array([5, 3, 3, 4]), array([4, 2, 0, 0]))

In [100]:
data1.shape

(4,)

In [104]:
data = np.array([[1, 2, 3, 4]
                 ,[4, 1, 0, 0]])

In [105]:
data.shape

(2, 4)

In [103]:
data = np.array(1)
data.shape

()

In [99]:
data1@data2

6

In [78]:
data3 = np.array([[1, 0], [2, 0], [3, 0]])
data4 = np.array([[1, 2], [3, 4], [0, 0]])
# data3@data4 #계산 불가능

In [79]:
data5 = np.array([[1, 2], [3, 0]])
data6 = np.array([[1, 0, 1, 0], [2, 0, 1, 1]])
data5@data6 # = data5.dot(data6) = np.dot(data5, data6) 

array([[5, 0, 3, 2],
       [3, 0, 3, 0]])

In [82]:
print(data5.dot(data6), np.dot(data5, data6), sep='\n')

[[5 0 3 2]
 [3 0 3 0]]
[[5 0 3 2]
 [3 0 3 0]]


In [85]:
data6 = np.array([[1, 0, 1, 0], [2, 0, 1, 1]])
data6

array([[1, 0, 1, 0],
       [2, 0, 1, 1]])

- data6을 전치시키고 싶다면? (대각선 회전)

In [86]:
data6.T

array([[1, 2],
       [0, 0],
       [1, 1],
       [0, 1]])

In [87]:
data7 = np.arange(10) # = for i in "range"를 기억하자
data7

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

- 전치가 아니라 내가 원하는 shape으로 바꾸고싶다면?

In [93]:
data7.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

- data7에서 짝수만 뽑아내고 싶다면?

In [95]:
data7[data7%2 == 0] # 조건식으로 지정 가능

array([0, 2, 4, 6, 8])