In [17]:
import numpy as np
import cv2
import os

In [37]:
def jpg_convert(dirname):#전체적 파일 불러요기
    list_jpg = os.listdir(dirname)
    
    for file in list_jpg:
        full_file = os.path.join(dirname, file)
        
        ext = os.path.splitext(full_file)[-1]
        
        if ext == '.jpg':
            transform(full_file)
        
        




def transform(filename):
    dirname = filename.replace("\\",'/')#파일명이 \ 나오기 때문에 / 로 바꾼다

    
    
    img = cv2.imread(dirname)
#     print(img)
#     print(filename)
    h, w = img.shape[:2]
#     new_filename = filename.replace('right_rotate','right')
    
#     M1 = cv2.getRotationMatrix2D((w/2, h/2), 45, 1)
    M2 = cv2.getRotationMatrix2D((w/2, h/2), 180, 1)#180도 변환
    
#     img2 = cv2.warpAffine(img, M1, (w, h))
    img3 = cv2.warpAffine(img, M2, (w, h))
    cv2.imwrite('D:/Data_collection/180/{}'.format(dirname.split('/')[-1]), img3)
    
#     cv2.imshow('45-Rotate', img2)
#     cv2.imshow('90-Rotate', img3)
    
    
#     cv2.waitKey(0)
#     cv2.destroyAllWindows()

In [38]:
jpg_convert('D:/Data_collection/180rotate/')

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
D:/Data_collection/180rotate/0052838140_0006_001.jpg
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
D:/Data_collection/180rotate/0052838140_0007_001.jpg
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

[[[248 247 243]
  [247 246 242]
  [244 243 239]
  ...
  [185 186 184]
  [186 187 185]
  [192 193 191]]

 [[253 252 248]
  [253 252 248]
  [251 250 246]
  ...
  [179 180 178]
  [180 181 179]
  [186 187 185]]

 [[255 255 251]
  [255 255 251]
  [255 254 250]
  ...
  [187 188 186]
  [190 191 189]
  [197 198 196]]

 ...

 [[207 204 196]
  [207 204 196]
  [207 204 196]
  ...
  [123 129 128]
  [125 131 130]
  [125 131 130]]

 [[207 204 196]
  [207 204 196]
  [207 204 196]
  ...
  [121 127 126]
  [122 128 127]
  [122 128 127]]

 [[207 204 196]
  [207 204 196]
  [207 204 196]
  ...
  [120 126 125]
  [120 126 125]
  [120 126 125]]]
D:/Data_collection/180rotate/0052838467_0012_001.jpg
[[[158 161 166]
  [157 160 165]
  [156 159 164]
  ...
  [177 180 184]
  [177 180 184]
  [178 181 185]]

 [[160 163 168]
  [159 162 167]
  [160 163 168]
  ...
  [177 180 184]
  [178 181 185]
  [178 181 185]]

 [[161 164 169]
  [162 165 170]
  [165 168 173]
  ...
  [179 182 186]
  [179 182 186]
  [179 182 186]]

 ...


[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
D:/Data_collection/180rotate/0052846132_0010_001.jpg
[[[ 37  30  35]
  [ 37  30  35]
  [ 37  30  35]
  ...
  [ 21  16 101]
  [ 22  15 100]
  [ 21  15  97]]

 [[ 33  26  31]
  [ 33  26  31]
  [ 33  26  31]
  ...
  [ 19  14  99]
  [ 20  13  98]
  [ 18  12  94]]

 [[ 35  28  33]
  [ 35  28  33]
  [ 35  28  33]
  ...
  [ 19  14  99]
  [ 20  13  98]
  [ 18  12  94]]

 ...

 [[241 244 248]
  [243 246 250]
  [244 247 251]
  ...
  [ 89 102  76]
  [ 90 103  77]
  [ 91 104  78]]

 [[240 245 248]
  [241 246 249]
  [243 248 251]
  ...
  [ 89 102  76]
  [ 90 103  77]
  [ 91 104  78]]

 [[239 

[[[138 128 118]
  [133 123 113]
  [135 125 115]
  ...
  [ 49  37  31]
  [ 48  36  30]
  [ 47  35  29]]

 [[139 129 119]
  [136 126 116]
  [136 126 116]
  ...
  [ 46  34  28]
  [ 45  33  27]
  [ 44  32  26]]

 [[139 130 120]
  [137 128 118]
  [136 127 117]
  ...
  [ 45  33  27]
  [ 44  32  26]
  [ 44  32  26]]

 ...

 [[223 229 224]
  [223 229 224]
  [223 229 224]
  ...
  [218 222 216]
  [218 222 216]
  [219 223 217]]

 [[223 229 224]
  [223 229 224]
  [223 229 224]
  ...
  [218 222 216]
  [218 222 216]
  [219 223 217]]

 [[223 229 224]
  [223 229 224]
  [223 229 224]
  ...
  [218 222 216]
  [218 222 216]
  [219 223 217]]]
D:/Data_collection/180rotate/0052869896_0009_001.jpg
[[[ 46  55  65]
  [ 58  67  77]
  [ 65  73  86]
  ...
  [136 145 155]
  [138 147 157]
  [122 131 141]]

 [[ 36  45  55]
  [ 54  63  73]
  [ 65  73  86]
  ...
  [134 143 157]
  [108 115 130]
  [ 87  96 110]]

 [[ 29  38  48]
  [ 55  64  74]
  [ 71  79  92]
  ...
  [113 121 144]
  [ 95 101 124]
  [100 108 131]]

 ...


[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [125 158 177]
  [125 158 177]
  [127 160 179]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [127 160 179]
  [128 161 180]
  [129 162 181]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [128 161 177]
  [129 162 178]
  [129 162 178]]

 ...

 [[174 191 177]
  [174 191 177]
  [175 192 178]
  ...
  [191 185 166]
  [181 175 156]
  [171 165 146]]

 [[175 192 178]
  [175 192 178]
  [176 193 179]
  ...
  [174 168 149]
  [163 157 138]
  [170 164 145]]

 [[178 195 181]
  [178 195 181]
  [179 196 182]
  ...
  [169 163 144]
  [160 154 135]
  [184 178 159]]]
D:/Data_collection/180rotate/0052876627_0007_001.jpg
[[[147 160 176]
  [150 163 179]
  [155 168 184]
  ...
  [ 45  70  96]
  [ 45  72  98]
  [ 44  71  97]]

 [[140 153 169]
  [143 156 172]
  [147 160 176]
  ...
  [ 49  74 100]
  [ 46  73  99]
  [ 42  69  95]]

 [[135 148 164]
  [137 150 166]
  [139 152 168]
  ...
  [ 52  77 103]
  [ 45  72  98]
  [ 38  65  91]]

 ...


  [0 0 0]]]
D:/Data_collection/180rotate/0052876990_0013_001.jpg
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
D:/Data_collection/180rotate/0052876990_0014_001.jpg
[[[118 111  91]
  [119 112  92]
  [122 115  95]
  ...
  [ 68  59  49]
  [ 71  62  52]
  [ 63  54  44]]

 [[122 115  95]
  [124 117  97]
  [126 119  99]
  ...
  [ 66  57  47]
  [ 71  62  52]
  [ 67  58  48]]

 [[113 106  86]
  [115 108  88]
  [119 112  92]
  ...
  [ 58  49  39]
  [ 65  56  46]
  [ 62  53  43]]

 ...

 [[238 230 213]
  [239 231 214]
  [238 231 212]
  ...
  [181 182 173]
  [181 182 173]
  [181 182 173]]

 [[229 222 205]
  [229 222 205]
  [231 225 206

  [0 0 0]]]
D:/Data_collection/180rotate/0052882215_0013_001.jpg
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
D:/Data_collection/180rotate/0052882215_0014_001.jpg
[[[  0  31  51]
  [ 20  53  73]
  [ 35  66  87]
  ...
  [ 20  38 115]
  [ 18  38 116]
  [ 15  35 113]]

 [[ 14  47  67]
  [ 13  46  66]
  [ 19  50  71]
  ...
  [ 22  40 117]
  [ 21  41 119]
  [ 18  38 116]]

 [[ 13  44  65]
  [ 11  42  63]
  [ 21  52  73]
  ...
  [ 24  44 122]
  [ 26  45 126]
  [ 24  43 124]]

 ...

 [[181 195 213]
  [182 196 214]
  [182 196 214]
  ...
  [136 144 161]
  [135 143 160]
  [135 143 160]]

 [[176 190 208]
  [177 191 209]
  [177 191 209

[[[170 196 210]
  [170 196 210]
  [170 196 210]
  ...
  [126 141 150]
  [127 142 151]
  [128 143 152]]

 [[170 196 210]
  [170 196 210]
  [170 196 210]
  ...
  [127 142 151]
  [129 144 153]
  [131 146 155]]

 [[170 196 210]
  [170 196 210]
  [170 196 210]
  ...
  [123 138 147]
  [126 141 150]
  [132 147 156]]

 ...

 [[192 221 236]
  [192 221 236]
  [192 221 236]
  ...
  [164 192 216]
  [164 192 216]
  [163 191 215]]

 [[192 221 236]
  [192 221 236]
  [192 221 236]
  ...
  [165 193 217]
  [164 192 216]
  [164 192 216]]

 [[192 221 236]
  [192 221 236]
  [192 221 236]
  ...
  [165 193 217]
  [165 193 217]
  [164 192 216]]]
D:/Data_collection/180rotate/0052910992_0008_001.jpg
[[[104 118 170]
  [106 120 172]
  [108 122 174]
  ...
  [ 86  92  99]
  [ 88  94  99]
  [ 84  90  95]]

 [[105 119 171]
  [106 120 172]
  [108 122 174]
  ...
  [109 115 122]
  [ 93  99 106]
  [ 73  78  87]]

 [[105 119 171]
  [107 121 173]
  [108 122 174]
  ...
  [ 80  85  94]
  [ 64  69  78]
  [ 54  59  68]]

 ...


[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
D:/Data_collection/180rotate/0053971533_0007_001.jpg
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
D:/Data_collection/180rotate/0053971533_0008_001.jpg
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

AttributeError: 'NoneType' object has no attribute 'shape'