# Numpy (수치해석용 패키지)

In [6]:
# import numpy 
import numpy as np  # numpy 매번치기 귀찮으면 as 쳐도 괜찮음 (이름은 협업시 편리한걸로)

### 배열 생성

In [8]:
data = np.array([1,2,3,4])
data, type(data)

(array([1, 2, 3, 4]), numpy.ndarray)

In [11]:
data_2 = np.zeros(5)   
data_2

array([0., 0., 0., 0., 0.])

In [12]:
data_3 = np.ones([3,5])
data_3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
data_4 = np.arange(0,10,1) #기억 for i in "range()""과 문법이 같음
data_4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
data_5 = np.linspace(1,10, 5)  #같은간격으로 (시작,끝,개수) arrange 만들어라
data_5

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [28]:
data_log = np.logspace(1,10, 5) #과학적표기법 (y값 1~10사이에서 로그간격으로 동일하게 나눴을때의 x값)
data_log

array([1.00000000e+01, 1.77827941e+03, 3.16227766e+05, 5.62341325e+07,
       1.00000000e+10])

In [23]:
data_6 = np.random.randint(1,10) #1~10사이의 random한 정수 리턴
data_6 = np.random.randint(1,10,size=(2,10)) # 2행 10열로 많이 만들어라
data_6

array([[8, 7, 3, 5, 1, 7, 8, 9, 8, 9],
       [7, 1, 5, 6, 4, 9, 9, 9, 8, 6]])

- data_6과 동일한 size의 0 array를 만들고 싶다면?

In [30]:
data_zero = np.zeros_like(data_6)
data_zero

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [31]:
data_one = np.ones_like(data_6)
data_one

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

### 배열 파악

In [32]:
data_one.ndim #배열의 차원 

2

In [33]:
data_one.shape #배열의 shape(몇행 몇열)

(2, 10)

In [34]:
data_one.dtype #배열의 데이터의 type

dtype('int32')

In [35]:
#리스트와 비교
data_list = [1, 2.0, 'hello' ] #다국적

data_array = np.array([1, 2.0, 'hello' ]) #단일민족 
data_array

array(['1', '2.0', 'hello'], dtype='<U32')

In [36]:
data_array.dtype #np는 한가지형태로 통일시켜버림 '<U32' 문자임

dtype('<U32')

In [37]:
data_array[0]

'1'

In [38]:
data_array.astypr('i') #배열의 데이터의 형변환 -> 형변환이 가능한 애들로 이루어져야 할수있음(에러)

AttributeError: 'numpy.ndarray' object has no attribute 'astypr'

In [40]:
data_array2 = np.array([1,2,3])
data_array2.astype('f')  #int -> float

array([1., 2., 3.], dtype=float32)

In [43]:
data_array2.astype('O')  #주의: 문자열은 'Object(대문자)' ('s'아니다!)

array([1, 2, 3], dtype=object)

### Numpy 강점

- 1개의 데이터 : Vector = 1차원 배열 = 하나의 데이터
- 여러개의 데이터: Matrix = 2차원 배열 = 여러개의 데이터 ( 벡터 합) 

1. 벡터화 연산이 가능하다. (모든원소에 3을 더하기, 곱하기 등)
2. 변환이 쉽다. (reshape)
3. 조건식으로 데이터 지정하기가 쉽다. (인덱싱자리에 조건식)
4. 계산이 빠르다.

In [46]:
#list와 비교 
a = [1,2,3]
c = a * 3 # 덧셈은 불가능 -> 원소하나하나에 접근해서 더할라면 복잡 ->array는 간단!
c

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [53]:
x = np.array(a)
y, z = x + 3 , x *3 
y, z

(array([4, 5, 6]), array([3, 6, 9]))

In [54]:
x + y

array([5, 7, 9])

In [55]:
x * y

array([ 4, 10, 18])

In [58]:
data1 = np.array([1,2,3,4])  #4행1열-> 벡터
data2 = np.array([4,1,0,0])  #4행1열 -> 벡터 

data1 + data2 , data1 * data2  #요소의 덧셈과 곱

(array([5, 3, 3, 4]), array([4, 2, 0, 0]))

In [97]:
data1.shape  #4행1열 확인

(4,)

In [98]:
data1 @ data2  #행렬 곱(1은 생략)

6

- () -> 1x1  -> scalar
- (n,)-> nx1 -> vector (열벡터) # np.array([1,2,3,4]) 꼴 => 열벡터끼리 합치면(덧셈아님) 행열로 됨 
- (n,m)-> nxm -> matrix

In [82]:
#참고
print(data1.dot(data2), np.dot(data1,data2), sep='\n') #교재에 나온 행렬 곱 

6
6


In [83]:
data3 = np.array([[1,0],[2,0],[3,0]])
data4 = np.array([[1,2],[3,4],[0,0]])

data3 + data4, data3* data4

(array([[2, 2],
        [5, 4],
        [3, 0]]), array([[1, 0],
        [6, 0],
        [0, 0]]))

In [75]:
data5 = np.array([[1,2],[3,0]])
data6 = np.array([[1,0,1,0],[2,0,1,1]])

data5 @ data6 

array([[5, 0, 3, 2],
       [3, 0, 3, 0]])

In [85]:
data6 = np.array([[1,0,1,0],[2,0,1,1]])
data6

array([[1, 0, 1, 0],
       [2, 0, 1, 1]])

- data6을 전치시키고 싶다면? (대각선 회전)

In [86]:
data6.T #문법 외우기 ★

array([[1, 2],
       [0, 0],
       [1, 1],
       [0, 1]])

In [88]:
data7 = np.arange(10) #for i in "range"를 기억하자 
data7

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

- 전치가 아니라 내가 원하는 shape으로 바꾸고 싶다면?

In [90]:
data7.reshape(5,2) # 전체 데이터 개수가 딱맞게 들어가야함 (작아도, 커도 안됨)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

- data7에서 짝수만 뽑아내고 싶다면?

In [95]:
data7[data7%2==0]  #인덱스에 조건식으로 지정 가능 

array([0, 2, 4, 6, 8])