In [3]:
import pandas as pd

Pandas에서 다루는 자료형 

- dataframe : table ( Series들의 합)
- Series : column

In [2]:
#numpy 와 비교
import numpy as np
data = np.array([1,2,3,4,5])
data

array([1, 2, 3, 4, 5])

In [3]:
data = pd.Series([1,2,3,4,5])
data

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [4]:
data_2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
data_2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [5]:
data_2 = pd.Series([[1,2,3,4,5],[6,7,8,9,10]]) 
data_2

#[1,2,3,4,5]가 하나의 셀에 전부 들어가 있는 형태 -> 변환이 필요함 -> DataFrame()

0     [1, 2, 3, 4, 5]
1    [6, 7, 8, 9, 10]
dtype: object

In [6]:
data_2 = pd.DataFrame([[1,2,3,4,5],[6,7,8,9,10]],
                      columns=['a','b','c','d','e'],  # 행, 열 이름도 설정 가능 
                     index=['one','two']) 
data_2

#이거를 이제 생성식으로 암기

a  b  c  d   e
one  1  2  3  4   5
two  6  7  8  9  10

In [7]:
data_2['a']  #열 뽑기

one    1
two    6
Name: a, dtype: int64

In [8]:
data_2[:] #처음부터 끝 열의 내용을 뽑아라 (즉, 전체를 보여줌)

a  b  c  d   e
one  1  2  3  4   5
two  6  7  8  9  10

In [9]:
# 행뽑기는 loc / iloc / ix  3개 있음
data_2.loc['one']  

# loc['행이름'] 암기!★   loc은 문자로 접근

a    1
b    2
c    3
d    4
e    5
Name: one, dtype: int64

In [10]:
data_2.iloc[0]   # iloc[숫자] 암기!★ integer의 i , 숫자 i 숫자 loc , iloc은 숫자로 접근

a    1
b    2
c    3
d    4
e    5
Name: one, dtype: int64

In [11]:
data_2.ix[0]  # ix[숫자|문자] 암기!★ i니까 숫자로 접근가능, 문자로도 접근 가능 => 둘다 됨(Xman)

C:\ProgramData\Anaconda3\envs\finance\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


a    1
b    2
c    3
d    4
e    5
Name: one, dtype: int64

In [12]:
data_2.ix['one']  

C:\ProgramData\Anaconda3\envs\finance\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


a    1
b    2
c    3
d    4
e    5
Name: one, dtype: int64

### 0530

In [13]:
data_3 = pd.DataFrame([[1,2,3],[4,5,6]])
data_3

0  1  2
0  1  2  3
1  4  5  6

In [14]:
data_3.iloc[0]

0    1
1    2
2    3
Name: 0, dtype: int64

In [15]:
data_3.iloc[1]

0    4
1    5
2    6
Name: 1, dtype: int64

In [16]:
data_3.loc[1] #되는 이유? -> 우리가 인덱스를 만들어주지 않으면 인덱스명(숫자)가 문자로 보기때문

0    4
1    5
2    6
Name: 1, dtype: int64

In [17]:
data_3.ix[1]

C:\ProgramData\Anaconda3\envs\finance\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


0    4
1    5
2    6
Name: 1, dtype: int64

In [18]:
data_3.iloc[:2]   #slicing 

0  1  2
0  1  2  3
1  4  5  6

In [19]:
data_3.loc[0:2]

0  1  2
0  1  2  3
1  4  5  6

In [20]:
data_3.iloc[:1] # iloc은 숫자를 넣어주니까 우리가 원래 아는 슬라이싱이 됨

0  1  2
0  1  2  3

In [21]:
data_3.loc[0:1] #loc은 원래 문자를 넣어주니까 ['시작row이름': '끝row이름'] 이 됨 (문자 인덱싱은 이러함)

0  1  2
0  1  2  3
1  4  5  6

In [22]:
#data = np.array([i for i in range(100)]) 
#data = data.reshape(10,10)
data = np.array([i for i in range(100)]).reshape(10,10)   #한번에 하기 
print(data)
data_3 = pd.DataFrame(data)
data_3

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


0   1   2   3   4   5   6   7   8   9
0   0   1   2   3   4   5   6   7   8   9
1  10  11  12  13  14  15  16  17  18  19
2  20  21  22  23  24  25  26  27  28  29
3  30  31  32  33  34  35  36  37  38  39
4  40  41  42  43  44  45  46  47  48  49
5  50  51  52  53  54  55  56  57  58  59
6  60  61  62  63  64  65  66  67  68  69
7  70  71  72  73  74  75  76  77  78  79
8  80  81  82  83  84  85  86  87  88  89
9  90  91  92  93  94  95  96  97  98  99

In [23]:
data_3.iloc[1:5]

0   1   2   3   4   5   6   7   8   9
1  10  11  12  13  14  15  16  17  18  19
2  20  21  22  23  24  25  26  27  28  29
3  30  31  32  33  34  35  36  37  38  39
4  40  41  42  43  44  45  46  47  48  49

In [24]:
data_3.loc[1:5]

0   1   2   3   4   5   6   7   8   9
1  10  11  12  13  14  15  16  17  18  19
2  20  21  22  23  24  25  26  27  28  29
3  30  31  32  33  34  35  36  37  38  39
4  40  41  42  43  44  45  46  47  48  49
5  50  51  52  53  54  55  56  57  58  59

In [25]:
data_3.ix[1:5] #ix는 둘다 다 될때 loc을 따른다.

C:\ProgramData\Anaconda3\envs\finance\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


0   1   2   3   4   5   6   7   8   9
1  10  11  12  13  14  15  16  17  18  19
2  20  21  22  23  24  25  26  27  28  29
3  30  31  32  33  34  35  36  37  38  39
4  40  41  42  43  44  45  46  47  48  49
5  50  51  52  53  54  55  56  57  58  59

Q. 위의 data_3에서 데이터 '54'를 지정해보세요.

In [26]:
data_3.iloc[5].iloc[4] #내가 

54

In [27]:
data_3[4].loc[5] #강사님

54

In [28]:
data_3.loc[5][4] #강사님2

54

In [29]:
data_3[5] #인덱싱할때 []하나만 적으면 column으로 인식

0     5
1    15
2    25
3    35
4    45
5    55
6    65
7    75
8    85
9    95
Name: 5, dtype: int32

In [30]:
data_3[3:5] #근데 슬라이싱하면 []하나는 로우로 간주

0   1   2   3   4   5   6   7   8   9
3  30  31  32  33  34  35  36  37  38  39
4  40  41  42  43  44  45  46  47  48  49

Q. 위의 data_3에서 데이터 '30~49'까지를 지정해보세요.

In [31]:
data_3.loc[3:4] #나

0   1   2   3   4   5   6   7   8   9
3  30  31  32  33  34  35  36  37  38  39
4  40  41  42  43  44  45  46  47  48  49

In [32]:
data_3[:][3:5] #강사님    #data[열][행]
#data_3[3:5][:] #반대로 해도 됨 (왜? -> 다음 퀴즈)  
#왤까???????????????????????????????????????
#예외라서 알아둘수밖에 없음... OMG~!

0   1   2   3   4   5   6   7   8   9
3  30  31  32  33  34  35  36  37  38  39
4  40  41  42  43  44  45  46  47  48  49

Q. 위의 data_3에서 데이터 '33,43'을 지정해보세요

In [33]:
data_3
data_3[3][3:5]

3    33
4    43
Name: 3, dtype: int32

In [34]:
data_3[3:5][3]  #얘도 됨 ,왤까? 

3    33
4    43
Name: 3, dtype: int32

- 인덱싱에서 [] 하나는 칼럼으로 인식 , 슬라이싱에서 [] 하나는 로우로 인식   
  - 잘 생각해보면 data['a'],data[0] 모두 열을 뽑아냄 (인덱싱)   
  - 또한 row(행)을 뽑기위해선 iloc, loc, ix 써야했음  
  - 그런데 행을 뽑을때 저 세개 안써도 슬라이싱을 써서 행 뽑기 된다고 생각하자!   
  
- 그래서 순서가 바뀌어도 인식하는건 같기 때문에 결과가 같다.  
  -data[열][행]  #가능  
  -data[열]      #가능  
  -data[행]      #에러 =>iloc, loc, ix 쓰거나 슬라이싱  
  -data[:]       #가능  
  -data[:][:]   ->???????????????????????  

In [35]:
data_3

0   1   2   3   4   5   6   7   8   9
0   0   1   2   3   4   5   6   7   8   9
1  10  11  12  13  14  15  16  17  18  19
2  20  21  22  23  24  25  26  27  28  29
3  30  31  32  33  34  35  36  37  38  39
4  40  41  42  43  44  45  46  47  48  49
5  50  51  52  53  54  55  56  57  58  59
6  60  61  62  63  64  65  66  67  68  69
7  70  71  72  73  74  75  76  77  78  79
8  80  81  82  83  84  85  86  87  88  89
9  90  91  92  93  94  95  96  97  98  99

In [36]:
data_3[:3][5]

0     5
1    15
2    25
Name: 5, dtype: int32

In [37]:
data_3.head() #디폴트 5줄
data_3.head(10)

0   1   2   3   4   5   6   7   8   9
0   0   1   2   3   4   5   6   7   8   9
1  10  11  12  13  14  15  16  17  18  19
2  20  21  22  23  24  25  26  27  28  29
3  30  31  32  33  34  35  36  37  38  39
4  40  41  42  43  44  45  46  47  48  49
5  50  51  52  53  54  55  56  57  58  59
6  60  61  62  63  64  65  66  67  68  69
7  70  71  72  73  74  75  76  77  78  79
8  80  81  82  83  84  85  86  87  88  89
9  90  91  92  93  94  95  96  97  98  99

In [38]:
data_3.tail()  # 데이터 총 몇개고 shape까지 알수 있음 

0   1   2   3   4   5   6   7   8   9
5  50  51  52  53  54  55  56  57  58  59
6  60  61  62  63  64  65  66  67  68  69
7  70  71  72  73  74  75  76  77  78  79
8  80  81  82  83  84  85  86  87  88  89
9  90  91  92  93  94  95  96  97  98  99

In [39]:
data_3.columns

RangeIndex(start=0, stop=10, step=1)

In [40]:
data_3.columns.dtype

dtype('int64')

In [41]:
data_3.index

RangeIndex(start=0, stop=10, step=1)

In [42]:
list(data_3) #column 값을 추출 (형변환 아님)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

- column의 순서를 바꾸고 싶다면?   
풀이) list 관점에서 생각하면 된다. 

In [43]:
cols = list(data_3)
print('원래 cols = {}'.format(cols))
cols.insert(0, cols.pop())
print('새로운 cols = {}'.format(cols))

원래 cols = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
새로운 cols = [9, 0, 1, 2, 3, 4, 5, 6, 7, 8]


In [46]:
data_3[cols]

9   0   1   2   3   4   5   6   7   8
0   9   0   1   2   3   4   5   6   7   8
1  19  10  11  12  13  14  15  16  17  18
2  29  20  21  22  23  24  25  26  27  28
3  39  30  31  32  33  34  35  36  37  38
4  49  40  41  42  43  44  45  46  47  48
5  59  50  51  52  53  54  55  56  57  58
6  69  60  61  62  63  64  65  66  67  68
7  79  70  71  72  73  74  75  76  77  78
8  89  80  81  82  83  84  85  86  87  88
9  99  90  91  92  93  94  95  96  97  98

In [45]:
#cols[1]=100   #그냥 이렇게 바꾸면 됨
#cols

In [49]:
data_3[0] = data_3[9]
data_3

0   1   2   3   4   5   6   7   8   9
0   9   1   2   3   4   5   6   7   8   9
1  19  11  12  13  14  15  16  17  18  19
2  29  21  22  23  24  25  26  27  28  29
3  39  31  32  33  34  35  36  37  38  39
4  49  41  42  43  44  45  46  47  48  49
5  59  51  52  53  54  55  56  57  58  59
6  69  61  62  63  64  65  66  67  68  69
7  79  71  72  73  74  75  76  77  78  79
8  89  81  82  83  84  85  86  87  88  89
9  99  91  92  93  94  95  96  97  98  99

In [53]:
#dict와 비교
dic = {'a': 1, 'b': 2}
dic

#데이터 수정 : 'a' <-3
dic['a'] = 3

#데이터 추가 : 'c'<-5
dic['c'] = 5

dic

{'a': 3, 'b': 2, 'c': 5}

- dataframe도 이와 같다. 

In [55]:
df_1 = pd.DataFrame([[1,2,3],[4,5,6]],columns = ['a','b','c'])
df_1

a  b  c
0  1  2  3
1  4  5  6

In [57]:
#데이터 수정 : 'a' <-'b' 
df_1['a']= df_1['b'] 

#데이터 추가 : 'd' <- 'c'
df_1['d']= df_1['c']

df_1

a  b  c  d
0  2  2  3  3
1  5  5  6  6

In [58]:
df_1['a'] += 3
df_1

a  b  c  d
0  5  2  3  3
1  8  5  6  6

In [61]:
df_1['a'] = df_1['b']*df_1['c']
df_1

a  b  c  d
0   6  2  3  3
1  30  5  6  6

In [62]:
# columns 지정하는 또다른 방법
df_1.a = df_1['b']*df_1['c']   # df_1.a와 df_1['a']는 같다.

0     6
1    30
Name: a, dtype: int64

- 아래와 같이 숫자로 형변환이 안되는 경우

In [69]:
df_2 = pd.DataFrame([['1,000','2,000','3,000'],  #데이터가 혼합되어 가면 1,000은 문자로 1은 숫자로 남아서 곤란하게 됨
                   ['1','2','3']])

In [70]:
df_2 

0      1      2
0  1,000  2,000  3,000
1      1      2      3

In [73]:
df_2.stack()

0  0    1,000
   1    2,000
   2    3,000
1  0        1
   1        2
   2        3
dtype: object

In [76]:
df_2 = df_2.stack().str.replace(",","").unstack() # 이렇게 해결 (데이터분석에서 많이 사용 ★ )

In [74]:
df_2 

0      1      2
0  1,000  2,000  3,000
1      1      2      3

In [79]:
df_2.astype(float)  #형변환도 가능

0       1       2
0  1000.0  2000.0  3000.0
1     1.0     2.0     3.0

In [78]:
df_2.astype(int)

0     1     2
0  1000  2000  3000
1     1     2     3

Q. 인덱스 a b c d 있을 때 a b 의 상위 인덱스로 A,  c d 는 B로 또 설정하고 싶으면? ( 데이터분석에서 많이 쓰임 ★) 

In [83]:
multi_ind = pd.MultiIndex.from_tuples(([('a',0),('a',1)]))

multi_col = [['b','b','b'],[0,1,2]]

In [84]:
df_mul = pd.DataFrame(df_2, 
                      columns=multi_col, index=multi_ind)
df_mul

b        
      0   1   2
a 0 NaN NaN NaN
  1 NaN NaN NaN

### Titanic Data

In [2]:
mkdir Dataset

In [13]:
dataset = pd.read_csv('Dataset/train.csv')
dataset
type(dataset)

pandas.core.frame.DataFrame

In [7]:
dataset.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [8]:
dataset.tail()

PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas   
887          888         1       1              Graham, Miss. Margaret Edith   
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"   
889          890         1       1                     Behr, Mr. Karl Howell   
890          891         0       3                       Dooley, Mr. Patrick   

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked  
886    male  27.0      0      0      211536  13.00   NaN        S  
887  female  19.0      0      0      112053  30.00   B42        S  
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S  
889    male  26.0      0      0      111369  30.00  C148        C  
890    male  32.0      0      0      370376   7.75   NaN        Q

In [9]:
dataset.loc[400:404]

PassengerId  Survived  Pclass                            Name     Sex  \
400          401         1       3              Niskanen, Mr. Juha    male   
401          402         0       3                 Adams, Mr. John    male   
402          403         0       3        Jussila, Miss. Mari Aina  female   
403          404         0       3  Hakkarainen, Mr. Pekka Pietari    male   
404          405         0       3         Oreskovic, Miss. Marija  female   

      Age  SibSp  Parch             Ticket     Fare Cabin Embarked  
400  39.0      0      0  STON/O 2. 3101289   7.9250   NaN        S  
401  26.0      0      0             341826   8.0500   NaN        S  
402  21.0      1      0               4137   9.8250   NaN        S  
403  28.0      1      0   STON/O2. 3101279  15.8500   NaN        S  
404  20.0      0      0             315096   8.6625   NaN        S

In [10]:
dataset.describe() #데이터의 통계

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [12]:
dataset.info() #데이터들의 정보 보여줌

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.6+ KB


- Age 는 결측치 있음   
  -Age는 float인데 결측치는 float이 아니고 버릴수 없을때 문제가 생김 -> 결측치 처리가 필요
- 1_Titanic_EDA 으로 넘어가서 자세히 보기!
  