In [1]:
import os
import cv2
import numpy as np

## image high convert

In [24]:
img_path = 'D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)'
file_path= 'D:/Data_collection/car_data/car_load_data/image_convert/000810_0001.jpg'
# img_path = img_path.replace("\\",'/')
print(img_path)

D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)


In [3]:
def adjust_gamma(image, gamma=1.0):
    invGamma = 1.0 / gamma
    table = np.array([((i / 255.0) ** invGamma) * 255
        for i in np.arange(0, 256)]).astype("uint8")

    return cv2.LUT(image, table)

In [4]:
#for i in os.listdir(img_path):
#    img_fullname = os.path.join(img_path, i)
#    print(img_fullname)
#    if os.path.isdir(img_fullname):
#        
#    img = cv2.imread(img_fullname)
#    gamma = 2.0                              # change the value here to get different result
#    adjusted = adjust_gamma(img, gamma=gamma)
#    cv2.imwrite(img_fullname.split('.')[0] + '_result.jpg', adjusted)

In [4]:
def image_pixel(dirname):
    try:
        files = os.listdir(dirname)
        
        for file in files:
        
            full_image = os.path.join(dirname, file)
            
            if os.path.isdir(full_image):
                image_pixel(full_image)
                
            else:
#                 full_image = full_image.replace('\\','/')
#                 print(full_image)
                ext = os.path.splitext(full_image)[-1]
                if ext == '.jpg':
            
                    img = cv2.imread(full_image)
                    print(full_image)
                    print(img)
                    gamma = 2.0

                    adjusted = adjust_gamma(img, gamma=gamma)
                    cv2.imwrite(full_image.split('.')[0]+'.jpg',adjusted)
        
        
        
    except PermissionError:
        pass

In [ ]:
image_pixel(img_path)

D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0001.jpg
[[[10  4 61]
  [13  7 54]
  [18 13 40]
  ...
  [21 21 21]
  [21 21 21]
  [21 21 21]]

 [[11  7 56]
  [13 10 49]
  [18 15 37]
  ...
  [21 21 21]
  [21 21 21]
  [21 21 21]]

 [[13 13 43]
  [15 15 39]
  [18 18 30]
  ...
  [21 21 21]
  [21 21 21]
  [21 21 21]]

 ...

 [[22 24 24]
  [22 24 24]
  [22 24 24]
  ...
  [22 24 24]
  [22 24 24]
  [22 24 24]]

 [[22 24 24]
  [22 24 24]
  [22 24 24]
  ...
  [22 24 24]
  [22 24 24]
  [22 24 24]]

 [[22 24 24]
  [22 24 24]
  [22 24 24]
  ...
  [22 24 24]
  [22 24 24]
  [22 24 24]]]
D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0002.jpg
[[[ 4  4 64]
  [ 8  8 56]
  [18 13 42]
  ...
  [21 21 21]
  [21 21 21]
  [21 21 21]]

 [[ 6  7 58]
  [10  9 51]
  [18 15 37]
  ...
  [21 21 21]
  [21 21 21]
  [21 21 21]]

 [[ 8 13 46]
  [11 14 42]
  [20 18 30]
  ...
  [21 21 21]
  [21 21 21]
  [21 21 21]]

 ...

D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0014.jpg
[[[ 26 118 101]
  [  6  77  61]
  [  1  33  22]
  ...
  [ 19  21  21]
  [ 19  21  21]
  [ 19  21  21]]

 [[  0  34  18]
  [  0  33  19]
  [  3  28  18]
  ...
  [ 19  21  21]
  [ 19  21  21]
  [ 19  21  21]]

 [[  0  30  15]
  [  0  31  20]
  [ 17  28  25]
  ...
  [ 19  21  21]
  [ 19  21  21]
  [ 19  21  21]]

 ...

 [[ 21  23  23]
  [ 21  23  23]
  [ 21  23  23]
  ...
  [ 53  79  86]
  [ 53  79  86]
  [ 53  79  86]]

 [[ 21  23  23]
  [ 21  23  23]
  [ 21  23  23]
  ...
  [ 52  78  85]
  [ 52  78  85]
  [ 52  78  85]]

 [[ 21  23  23]
  [ 21  23  23]
  [ 21  23  23]
  ...
  [ 53  79  86]
  [ 53  79  86]
  [ 53  79  86]]]
D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0015.jpg
[[[ 36 113 110]
  [ 61 119 118]
  [  0  21  21]
  ...
  [ 23  21  21]
  [ 23  21  21]
  [ 23  21  21]]

 [[  0  27  26]
  [  0  35  33]
  [  3  21  20]
  

D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0027.jpg
[[[  3  46 113]
  [  0  25  74]
  [ 15  15  33]
  ...
  [ 19  21  21]
  [ 19  21  21]
  [ 19  21  21]]

 [[  0  15  61]
  [  0  16  52]
  [ 20  20  34]
  ...
  [ 19  21  21]
  [ 19  21  21]
  [ 19  21  21]]

 [[ 14  25  33]
  [ 21  27  34]
  [ 28  24  30]
  ...
  [ 19  21  21]
  [ 19  21  21]
  [ 19  21  21]]

 ...

 [[ 22  24  24]
  [ 22  24  24]
  [ 22  24  24]
  ...
  [ 34  50  62]
  [ 34  50  62]
  [ 34  50  62]]

 [[ 22  24  24]
  [ 22  24  24]
  [ 22  24  24]
  ...
  [ 34  50  62]
  [ 34  50  62]
  [ 34  50  62]]

 [[ 22  24  24]
  [ 22  24  24]
  [ 22  24  24]
  ...
  [ 34  50  62]
  [ 34  50  62]
  [ 34  50  62]]]
D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0028.jpg
[[[ 41  84 123]
  [ 48  83 116]
  [  0  19  37]
  ...
  [ 22  23  21]
  [ 22  23  21]
  [ 22  23  21]]

 [[  0  21  54]
  [  0  24  50]
  [  0  14  30]
  

D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0040.jpg
[[[ 50  31 152]
  [105  92 184]
  [ 20  16  52]
  ...
  [ 21  20  22]
  [ 21  20  22]
  [ 21  20  22]]

 [[  8   0  89]
  [ 10   2  72]
  [ 12  11  37]
  ...
  [ 21  20  22]
  [ 21  20  22]
  [ 21  20  22]]

 [[ 13  18  49]
  [  5  11  34]
  [ 20  24  29]
  ...
  [ 21  20  22]
  [ 21  20  22]
  [ 21  20  22]]

 ...

 [[ 21  23  23]
  [ 21  23  23]
  [ 21  23  23]
  ...
  [ 21  23  23]
  [ 21  23  23]
  [ 21  23  23]]

 [[ 21  23  23]
  [ 21  23  23]
  [ 21  23  23]
  ...
  [ 21  23  23]
  [ 21  23  23]
  [ 21  23  23]]

 [[ 21  23  23]
  [ 21  23  23]
  [ 21  23  23]
  ...
  [ 21  23  23]
  [ 21  23  23]
  [ 21  23  23]]]
D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0041.jpg
[[[ 30  51 156]
  [ 51  67 150]
  [ 11  16  55]
  ...
  [ 21  22  20]
  [ 21  22  20]
  [ 21  22  20]]

 [[  0   0  82]
  [  3  14  76]
  [  8  10  40]
  

D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0053.jpg
[[[ 19  42 168]
  [  0  16 113]
  [ 10   9  51]
  ...
  [ 19  21  21]
  [ 19  21  21]
  [ 19  21  21]]

 [[  0   0  94]
  [  0   1  75]
  [ 11  11  41]
  ...
  [ 19  21  21]
  [ 19  21  21]
  [ 19  21  21]]

 [[  1   9  46]
  [ 14  18  46]
  [ 23  23  29]
  ...
  [ 19  21  21]
  [ 19  21  21]
  [ 19  21  21]]

 ...

 [[ 21  23  23]
  [ 21  23  23]
  [ 21  23  23]
  ...
  [ 21  23  23]
  [ 21  23  23]
  [ 21  23  23]]

 [[ 22  24  24]
  [ 22  24  24]
  [ 22  24  24]
  ...
  [ 21  23  23]
  [ 21  23  23]
  [ 21  23  23]]

 [[ 22  24  24]
  [ 22  24  24]
  [ 22  24  24]
  ...
  [ 21  23  23]
  [ 21  23  23]
  [ 21  23  23]]]
D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0054.jpg
[[[ 31  39 183]
  [ 47  54 163]
  [  8  13  52]
  ...
  [ 21  21  21]
  [ 21  21  21]
  [ 21  21  21]]

 [[  0   0  96]
  [  0   3  86]
  [  3   9  38]
  

D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0065.jpg
[[[ 27  56 201]
  [ 42  63 178]
  [  4   8  59]
  ...
  [ 17  22  21]
  [ 17  22  21]
  [ 17  22  21]]

 [[  0   0  99]
  [  0   1  87]
  [  1   4  42]
  ...
  [ 17  22  21]
  [ 17  22  21]
  [ 17  22  21]]

 [[  7  12  51]
  [  6   8  38]
  [ 22  21  30]
  ...
  [ 17  22  21]
  [ 17  22  21]
  [ 17  22  21]]

 ...

 [[ 21  23  23]
  [ 21  23  23]
  [ 21  23  23]
  ...
  [ 21  23  23]
  [ 21  23  23]
  [ 21  23  23]]

 [[ 21  23  23]
  [ 21  23  23]
  [ 21  23  23]
  ...
  [ 21  23  23]
  [ 21  23  23]
  [ 21  23  23]]

 [[ 21  23  23]
  [ 21  23  23]
  [ 21  23  23]
  ...
  [ 21  23  23]
  [ 21  23  23]
  [ 21  23  23]]]
D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0066.jpg
[[[ 26  47 209]
  [ 65  86 208]
  [  0  11  54]
  ...
  [ 20  20  20]
  [ 20  20  20]
  [ 19  19  19]]

 [[  0   0 112]
  [  0   7 100]
  [  3  18  50]
  

D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0077.jpg
[[[ 30  56 222]
  [ 31  50 179]
  [ 13  13  67]
  ...
  [ 20  20  20]
  [ 20  20  20]
  [ 20  20  20]]

 [[  0   0 111]
  [  0   0  96]
  [  9   8  47]
  ...
  [ 20  20  20]
  [ 20  20  20]
  [ 20  20  20]]

 [[  7   7  55]
  [ 11  10  44]
  [ 25  18  25]
  ...
  [ 20  20  20]
  [ 20  20  20]
  [ 20  20  20]]

 ...

 [[ 21  23  23]
  [ 21  23  23]
  [ 21  23  23]
  ...
  [ 21  23  23]
  [ 21  23  23]
  [ 21  23  23]]

 [[ 21  23  23]
  [ 21  23  23]
  [ 21  23  23]
  ...
  [ 21  23  23]
  [ 21  23  23]
  [ 21  23  23]]

 [[ 21  23  23]
  [ 21  23  23]
  [ 21  23  23]
  ...
  [ 21  23  23]
  [ 21  23  23]
  [ 21  23  23]]]
D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0078.jpg
[[[ 30  50 222]
  [ 19  37 168]
  [  3  13  61]
  ...
  [ 21  21  21]
  [ 21  21  21]
  [ 21  21  21]]

 [[  0   0 113]
  [  0   0  94]
  [  0   6  40]
  

D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0090.jpg
[[[ 20  80   0]
  [ 90 138  72]
  [ 14  38   6]
  ...
  [ 19  21  21]
  [ 19  21  21]
  [ 19  21  21]]

 [[  0  46   0]
  [  4  43   0]
  [  7  27   4]
  ...
  [ 19  21  21]
  [ 19  21  21]
  [ 19  21  21]]

 [[  9  36   3]
  [  9  31   6]
  [ 25  34  24]
  ...
  [ 18  20  20]
  [ 18  20  20]
  [ 18  20  20]]

 ...

 [[ 20  22  22]
  [ 20  22  22]
  [ 20  22  22]
  ...
  [ 19  23  24]
  [ 19  23  24]
  [ 19  23  24]]

 [[ 20  22  22]
  [ 20  22  22]
  [ 20  22  22]
  ...
  [ 19  23  24]
  [ 19  23  24]
  [ 19  23  24]]

 [[ 20  22  22]
  [ 20  22  22]
  [ 20  22  22]
  ...
  [ 19  23  24]
  [ 19  23  24]
  [ 19  23  24]]]
D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0091.jpg
[[[ 8 17  0]
  [43 54 34]
  [14 23 10]
  ...
  [19 21 21]
  [19 21 21]
  [19 21 21]]

 [[20 26  9]
  [25 32 17]
  [15 23 12]
  ...
  [19 21 21]
  [19 21 2

D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0118.jpg
[[[ 26  77  57]
  [130 169 154]
  [ 14  28  26]
  ...
  [ 19  19  19]
  [ 19  19  19]
  [ 19  19  19]]

 [[  0  31  15]
  [  0  30  17]
  [ 13  24  22]
  ...
  [ 20  20  20]
  [ 19  19  19]
  [ 19  19  19]]

 [[  8  25  14]
  [ 11  24  16]
  [ 21  26  25]
  ...
  [ 20  20  20]
  [ 20  20  20]
  [ 19  19  19]]

 ...

 [[ 20  22  22]
  [ 20  22  22]
  [ 20  22  22]
  ...
  [ 20  22  22]
  [ 20  22  22]
  [ 20  22  22]]

 [[ 20  22  22]
  [ 20  22  22]
  [ 20  22  22]
  ...
  [ 20  22  22]
  [ 20  22  22]
  [ 20  22  22]]

 [[ 20  22  22]
  [ 20  22  22]
  [ 20  22  22]
  ...
  [ 20  22  22]
  [ 20  22  22]
  [ 20  22  22]]]
D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0119.jpg
[[[ 34  77  68]
  [ 82 116 109]
  [ 15  32  28]
  ...
  [ 20  20  20]
  [ 20  20  20]
  [ 20  20  20]]

 [[  0  28  21]
  [  5  31  25]
  [  6  17  14]
  

D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0137.jpg
[[[ 48  77  92]
  [ 83 107 119]
  [ 13  23  30]
  ...
  [ 20  20  20]
  [ 20  20  20]
  [ 20  20  20]]

 [[  0  19  31]
  [ 12  31  39]
  [ 11  20  24]
  ...
  [ 20  20  20]
  [ 20  20  20]
  [ 20  20  20]]

 [[  5  16  24]
  [  7  16  20]
  [ 21  23  24]
  ...
  [ 20  20  20]
  [ 20  20  20]
  [ 20  20  20]]

 ...

 [[ 20  22  22]
  [ 20  22  22]
  [ 20  22  22]
  ...
  [ 20  22  22]
  [ 20  22  22]
  [ 20  22  22]]

 [[ 20  22  22]
  [ 20  22  22]
  [ 20  22  22]
  ...
  [ 20  22  22]
  [ 20  22  22]
  [ 20  22  22]]

 [[ 20  22  22]
  [ 20  22  22]
  [ 20  22  22]
  ...
  [ 20  22  22]
  [ 20  22  22]
  [ 20  22  22]]]
D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0138.jpg
[[[40 87 91]
  [53 90 94]
  [13 26 34]
  ...
  [20 20 20]
  [20 20 20]
  [20 20 20]]

 [[ 0 26 31]
  [ 0 28 33]
  [ 4 16 22]
  ...
  [20 20 20]
  [20 20 2

D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0156.jpg
[[[ 35  77 124]
  [  3  37  73]
  [  2  15  31]
  ...
  [ 19  19  19]
  [ 19  19  19]
  [ 18  18  18]]

 [[  0  17  53]
  [  0  14  41]
  [  5  17  27]
  ...
  [ 19  19  19]
  [ 19  19  19]
  [ 18  18  18]]

 [[  0  15  28]
  [  7  20  28]
  [ 15  25  25]
  ...
  [ 19  19  19]
  [ 19  19  19]
  [ 19  19  19]]

 ...

 [[ 20  22  22]
  [ 20  22  22]
  [ 20  22  22]
  ...
  [ 20  22  22]
  [ 19  21  21]
  [ 19  21  21]]

 [[ 20  22  22]
  [ 20  22  22]
  [ 20  22  22]
  ...
  [ 20  22  22]
  [ 19  21  21]
  [ 19  21  21]]

 [[ 20  22  22]
  [ 20  22  22]
  [ 20  22  22]
  ...
  [ 20  22  22]
  [ 19  21  21]
  [ 19  21  21]]]
D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0157.jpg
[[[ 42  78 118]
  [ 24  55  88]
  [ 10  27  46]
  ...
  [ 20  20  20]
  [ 20  20  20]
  [ 20  20  20]]

 [[  0  14  45]
  [  0  16  40]
  [  4  18  30]
  

D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0174.jpg
[[[ 22  90 137]
  [  0  49  89]
  [  0  15  41]
  ...
  [ 20  20  20]
  [ 20  20  20]
  [ 20  20  20]]

 [[  0  14  49]
  [  0  17  46]
  [  7  19  37]
  ...
  [ 20  20  20]
  [ 20  20  20]
  [ 20  20  20]]

 [[  0  15  29]
  [  0  21  29]
  [ 18  23  24]
  ...
  [ 20  20  20]
  [ 20  20  20]
  [ 20  20  20]]

 ...

 [[ 20  22  22]
  [ 20  22  22]
  [ 20  22  22]
  ...
  [ 19  21  21]
  [ 18  20  20]
  [ 18  20  20]]

 [[ 20  22  22]
  [ 20  22  22]
  [ 20  22  22]
  ...
  [ 19  21  21]
  [ 18  20  20]
  [ 18  20  20]]

 [[ 20  22  22]
  [ 20  22  22]
  [ 20  22  22]
  ...
  [ 19  21  21]
  [ 18  20  20]
  [ 18  20  20]]]
D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0175.jpg
[[[ 24  88 146]
  [  7  56 100]
  [  7  26  47]
  ...
  [ 18  20  20]
  [ 18  20  20]
  [ 18  20  20]]

 [[  0  14  60]
  [  0  14  49]
  [  4  17  33]
  

D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0191.jpg
[[[ 28  71 204]
  [  1  34 137]
  [  0  13  52]
  ...
  [ 20  20  20]
  [ 20  20  20]
  [ 20  20  20]]

 [[  0   0  90]
  [  0   0  74]
  [  2  12  42]
  ...
  [ 20  20  20]
  [ 20  20  20]
  [ 20  20  20]]

 [[  0  10  51]
  [  1  15  44]
  [ 17  19  29]
  ...
  [ 20  20  20]
  [ 20  20  20]
  [ 20  20  20]]

 ...

 [[ 20  22  22]
  [ 20  22  22]
  [ 20  22  22]
  ...
  [ 20  22  22]
  [ 20  22  22]
  [ 20  22  22]]

 [[ 20  22  22]
  [ 20  22  22]
  [ 20  22  22]
  ...
  [ 20  22  22]
  [ 20  22  22]
  [ 20  22  22]]

 [[ 20  22  22]
  [ 20  22  22]
  [ 20  22  22]
  ...
  [ 20  22  22]
  [ 20  22  22]
  [ 20  22  22]]]
D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0192.jpg
[[[ 32  86 201]
  [ 45  88 175]
  [  0  16  52]
  ...
  [ 20  20  20]
  [ 20  20  20]
  [ 20  20  20]]

 [[  0   0  86]
  [  0   7  73]
  [  0  11  38]
  

D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0204.jpg
[[[ 24  87 202]
  [  0   1  89]
  [  0  10  47]
  ...
  [ 20  20  20]
  [ 20  20  20]
  [ 20  20  20]]

 [[  0   4  95]
  [  0   6  74]
  [  5  16  43]
  ...
  [ 20  20  20]
  [ 20  20  20]
  [ 20  20  20]]

 [[  0  12  49]
  [  2  15  41]
  [ 15  19  24]
  ...
  [ 20  20  20]
  [ 20  20  20]
  [ 20  20  20]]

 ...

 [[ 20  22  22]
  [ 20  22  22]
  [ 20  22  22]
  ...
  [ 20  22  22]
  [ 20  22  22]
  [ 20  22  22]]

 [[ 20  22  22]
  [ 20  22  22]
  [ 20  22  22]
  ...
  [ 20  22  22]
  [ 20  22  22]
  [ 20  22  22]]

 [[ 20  22  22]
  [ 20  22  22]
  [ 20  22  22]
  ...
  [ 20  22  22]
  [ 20  22  22]
  [ 20  22  22]]]
D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0205.jpg
[[[ 28  89 205]
  [  0  43 134]
  [  0  10  49]
  ...
  [ 20  20  20]
  [ 20  20  20]
  [ 20  20  20]]

 [[  0   3  91]
  [  0   7  75]
  [  1  13  41]
  

D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0216.jpg
[[[ 29  63 246]
  [ 51  79 217]
  [  1   9  62]
  ...
  [ 18  20  20]
  [ 18  20  20]
  [ 18  20  20]]

 [[  0   0 122]
  [  0   0 103]
  [  1   7  44]
  ...
  [ 18  20  20]
  [ 18  20  20]
  [ 18  20  20]]

 [[  0  10  57]
  [  2   9  42]
  [ 23  18  27]
  ...
  [ 18  20  20]
  [ 18  20  20]
  [ 18  20  20]]

 ...

 [[ 20  22  22]
  [ 20  22  22]
  [ 20  22  22]
  ...
  [ 20  22  22]
  [ 20  22  22]
  [ 20  22  22]]

 [[ 20  22  22]
  [ 20  22  22]
  [ 20  22  22]
  ...
  [ 20  22  22]
  [ 20  22  22]
  [ 20  22  22]]

 [[ 20  22  22]
  [ 20  22  22]
  [ 20  22  22]
  ...
  [ 20  22  22]
  [ 20  22  22]
  [ 20  22  22]]]
D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0217.jpg
[[[40 60 15]
  [61 78 41]
  [16 25  5]
  ...
  [18 20 20]
  [18 20 20]
  [18 20 20]]

 [[12 28  0]
  [19 33  5]
  [12 19  4]
  ...
  [18 20 20]
  [18 20 2

D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0240.jpg
[[[ 39  55  48]
  [139 153 147]
  [ 18  23  21]
  ...
  [ 20  20  20]
  [ 20  20  20]
  [ 20  20  20]]

 [[  9  23  17]
  [ 18  30  24]
  [ 16  21  19]
  ...
  [ 20  20  20]
  [ 20  20  20]
  [ 20  20  20]]

 [[ 20  27  24]
  [ 16  23  20]
  [ 20  26  21]
  ...
  [ 20  20  20]
  [ 20  20  20]
  [ 20  20  20]]

 ...

 [[ 20  22  22]
  [ 20  22  22]
  [ 20  22  22]
  ...
  [ 20  22  22]
  [ 20  22  22]
  [ 20  22  22]]

 [[ 20  22  22]
  [ 20  22  22]
  [ 20  22  22]
  ...
  [ 20  22  22]
  [ 20  22  22]
  [ 20  22  22]]

 [[ 20  22  22]
  [ 20  22  22]
  [ 20  22  22]
  ...
  [ 20  22  22]
  [ 20  22  22]
  [ 20  22  22]]]
D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0241.jpg
[[[ 41  52  50]
  [110 121 119]
  [ 17  25  24]
  ...
  [ 18  20  20]
  [ 18  20  20]
  [ 18  20  20]]

 [[ 11  19  18]
  [ 18  26  25]
  [  9  17  16]
  

D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0257.jpg
[[[ 25  74  84]
  [ 54  93 101]
  [  2  18  24]
  ...
  [ 18  20  20]
  [ 18  20  20]
  [ 18  20  20]]

 [[  0  20  28]
  [  0  29  36]
  [  7  19  23]
  ...
  [ 18  20  20]
  [ 18  20  20]
  [ 18  20  20]]

 [[  0  16  19]
  [  1  13  17]
  [ 19  22  26]
  ...
  [ 18  20  20]
  [ 18  20  20]
  [ 18  20  20]]

 ...

 [[ 20  22  22]
  [ 20  22  22]
  [ 20  22  22]
  ...
  [ 20  22  22]
  [ 20  22  22]
  [ 20  22  22]]

 [[ 20  22  22]
  [ 20  22  22]
  [ 20  22  22]
  ...
  [ 20  22  22]
  [ 20  22  22]
  [ 20  22  22]]

 [[ 20  22  22]
  [ 20  22  22]
  [ 20  22  22]
  ...
  [ 20  22  22]
  [ 20  22  22]
  [ 20  22  22]]]
D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0258.jpg
[[[39 62 77]
  [59 78 91]
  [ 7 22 31]
  ...
  [19 19 19]
  [19 19 19]
  [19 19 19]]

 [[ 0 17 30]
  [ 9 25 37]
  [ 3 14 22]
  ...
  [19 19 19]
  [19 19 1

D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0272.jpg
[[[ 23  52 103]
  [ 78 100 141]
  [  6  17  39]
  ...
  [ 18  20  20]
  [ 18  20  20]
  [ 18  20  20]]

 [[  0  10  51]
  [  1  19  50]
  [  5  12  27]
  ...
  [ 18  20  20]
  [ 18  20  20]
  [ 18  20  20]]

 [[ 13  20  39]
  [  4  12  25]
  [ 23  28  27]
  ...
  [ 18  20  20]
  [ 18  20  20]
  [ 18  20  20]]

 ...

 [[ 20  22  22]
  [ 20  22  22]
  [ 20  22  22]
  ...
  [ 19  21  21]
  [ 19  21  21]
  [ 19  21  21]]

 [[ 20  22  22]
  [ 20  22  22]
  [ 20  22  22]
  ...
  [ 19  21  21]
  [ 19  21  21]
  [ 19  21  21]]

 [[ 20  22  22]
  [ 20  22  22]
  [ 20  22  22]
  ...
  [ 19  21  21]
  [ 19  21  21]
  [ 19  21  21]]]
D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0273.jpg
[[[ 37  67 102]
  [ 49  76 102]
  [  3  20  29]
  ...
  [ 18  20  20]
  [ 18  20  20]
  [ 18  20  20]]

 [[  0  14  42]
  [  3  22  43]
  [  2  14  20]
  

D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0286.jpg
[[[ 21  28 121]
  [ 84  90 161]
  [  9  16  41]
  ...
  [ 19  19  19]
  [ 19  19  19]
  [ 19  19  19]]

 [[  0   0  71]
  [  6  12  65]
  [ 10  14  32]
  ...
  [ 19  19  19]
  [ 19  19  19]
  [ 19  19  19]]

 [[ 10  17  44]
  [  7  14  31]
  [ 22  24  24]
  ...
  [ 19  19  19]
  [ 19  19  19]
  [ 19  19  19]]

 ...

 [[ 20  22  22]
  [ 20  22  22]
  [ 20  22  22]
  ...
  [ 19  21  21]
  [ 18  20  20]
  [ 18  20  20]]

 [[ 20  22  22]
  [ 20  22  22]
  [ 20  22  22]
  ...
  [ 19  21  21]
  [ 18  20  20]
  [ 18  20  20]]

 [[ 20  22  22]
  [ 20  22  22]
  [ 20  22  22]
  ...
  [ 19  21  21]
  [ 18  20  20]
  [ 18  20  20]]]
D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0287.jpg
[[[ 37  38 136]
  [ 58  61 136]
  [  7  11  46]
  ...
  [ 18  20  20]
  [ 18  20  20]
  [ 18  20  20]]

 [[  0   0  69]
  [  3   7  66]
  [  0   3  28]
  

[[[ 29  31 161]
  [ 45  49 151]
  [  0   4  51]
  ...
  [ 17  19  19]
  [ 17  19  19]
  [ 17  19  19]]

 [[  0   0  88]
  [  0   1  76]
  [  0   2  35]
  ...
  [ 17  19  19]
  [ 17  19  19]
  [ 17  19  19]]

 [[  9  11  42]
  [  6   8  32]
  [ 21  20  29]
  ...
  [ 17  19  19]
  [ 17  19  19]
  [ 17  19  19]]

 ...

 [[ 19  21  21]
  [ 19  21  21]
  [ 19  21  21]
  ...
  [ 19  21  21]
  [ 19  21  21]
  [ 19  21  21]]

 [[ 19  21  21]
  [ 19  21  21]
  [ 19  21  21]
  ...
  [ 19  21  21]
  [ 19  21  21]
  [ 19  21  21]]

 [[ 19  21  21]
  [ 19  21  21]
  [ 19  21  21]
  ...
  [ 19  21  21]
  [ 19  21  21]
  [ 19  21  21]]]
D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0303.jpg
[[[ 25  36 174]
  [ 41  52 156]
  [ 14  20  57]
  ...
  [ 19  19  19]
  [ 19  19  19]
  [ 19  19  19]]

 [[  0   0  97]
  [  0   6  85]
  [ 12  15  43]
  ...
  [ 19  19  19]
  [ 19  19  19]
  [ 19  19  19]]

 [[  2   8  43]
  [  5   9  34]
  [ 24  20  31]
  ...


D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0319.jpg
[[[ 38 133 182]
  [  3  79 115]
  [  0  29  42]
  ...
  [ 22  22  22]
  [ 24  22  22]
  [ 24  22  22]]

 [[  0  22  59]
  [  0  14  43]
  [  0  18  25]
  ...
  [ 22  22  22]
  [ 22  22  22]
  [ 22  22  22]]

 [[  0  18  36]
  [  0  18  29]
  [  9  21  21]
  ...
  [ 21  24  22]
  [ 21  24  22]
  [ 21  24  22]]

 ...

 [[ 19  21  21]
  [ 19  21  21]
  [ 19  21  21]
  ...
  [ 19  21  21]
  [ 19  21  21]
  [ 19  21  21]]

 [[ 19  21  21]
  [ 19  21  21]
  [ 19  21  21]
  ...
  [ 19  21  21]
  [ 19  21  21]
  [ 19  21  21]]

 [[ 19  21  21]
  [ 19  21  21]
  [ 19  21  21]
  ...
  [ 19  21  21]
  [ 19  21  21]
  [ 19  21  21]]]
D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0320.jpg
[[[ 18 128 200]
  [  0  59 115]
  [  0  15  40]
  ...
  [ 26  38  32]
  [ 27  39  33]
  [ 27  39  33]]

 [[  0  19  73]
  [  0   7  48]
  [  0  11  29]
  

D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0333.jpg
[[[ 36  18 219]
  [ 51  39 191]
  [ 10   6  65]
  ...
  [ 19  19  19]
  [ 19  19  19]
  [ 19  19  19]]

 [[  0   0 123]
  [  0   0 103]
  [  1   0  41]
  ...
  [ 19  19  19]
  [ 19  19  19]
  [ 19  19  19]]

 [[  0   3  61]
  [  1   5  46]
  [ 19  19  31]
  ...
  [ 19  19  19]
  [ 19  19  19]
  [ 19  19  19]]

 ...

 [[ 19  21  21]
  [ 19  21  21]
  [ 19  21  21]
  ...
  [ 19  21  21]
  [ 19  21  21]
  [ 19  21  21]]

 [[ 19  21  21]
  [ 19  21  21]
  [ 19  21  21]
  ...
  [ 19  21  21]
  [ 19  21  21]
  [ 19  21  21]]

 [[ 19  21  21]
  [ 19  21  21]
  [ 19  21  21]
  ...
  [ 19  21  21]
  [ 19  21  21]
  [ 19  21  21]]]
D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0334.jpg
[[[ 32  22 219]
  [102  98 247]
  [  0   6  61]
  ...
  [ 19  19  19]
  [ 19  19  19]
  [ 19  19  19]]

 [[  0   0 124]
  [  0   0 103]
  [  3  10  49]
  

D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0345.jpg
[[[34 51 17]
  [72 87 59]
  [18 28 12]
  ...
  [17 19 19]
  [17 19 19]
  [17 19 19]]

 [[13 28  0]
  [25 39 15]
  [11 20  7]
  ...
  [17 19 19]
  [17 19 19]
  [17 19 19]]

 [[14 28 10]
  [14 25  9]
  [13 20 13]
  ...
  [17 19 19]
  [17 19 19]
  [17 19 19]]

 ...

 [[19 21 21]
  [19 21 21]
  [19 21 21]
  ...
  [19 21 21]
  [19 21 21]
  [19 21 21]]

 [[19 21 21]
  [19 21 21]
  [19 21 21]
  ...
  [19 21 21]
  [19 21 21]
  [19 21 21]]

 [[19 21 21]
  [19 21 21]
  [19 21 21]
  ...
  [19 21 21]
  [19 21 21]
  [19 21 21]]]
D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0346.jpg
[[[ 34  56  21]
  [146 164 135]
  [ 17  27  11]
  ...
  [ 17  19  19]
  [ 17  19  19]
  [ 17  19  19]]

 [[ 11  29   0]
  [ 18  32   8]
  [ 16  25  12]
  ...
  [ 17  19  19]
  [ 17  19  19]
  [ 17  19  19]]

 [[ 13  25   7]
  [ 12  22   6]
  [ 20  25  16]
  ...


D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0371.jpg
[[[39 65 59]
  [42 64 59]
  [ 9 24 20]
  ...
  [19 19 19]
  [19 19 19]
  [19 19 19]]

 [[ 0 22 17]
  [ 9 29 24]
  [ 6 20 16]
  ...
  [19 19 19]
  [19 19 19]
  [19 19 19]]

 [[ 4 18 14]
  [ 5 16 13]
  [14 23 20]
  ...
  [19 19 19]
  [19 19 19]
  [19 19 19]]

 ...

 [[19 21 21]
  [19 21 21]
  [19 21 21]
  ...
  [19 21 21]
  [19 21 21]
  [19 21 21]]

 [[19 21 21]
  [19 21 21]
  [19 21 21]
  ...
  [19 21 21]
  [19 21 21]
  [19 21 21]]

 [[19 21 21]
  [19 21 21]
  [19 21 21]
  ...
  [19 21 21]
  [19 21 21]
  [19 21 21]]]
D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0372.jpg
[[[35 71 65]
  [59 89 84]
  [12 25 23]
  ...
  [17 19 19]
  [17 19 19]
  [17 19 19]]

 [[ 0 26 22]
  [ 4 25 22]
  [ 7 18 16]
  ...
  [17 19 19]
  [17 19 19]
  [17 19 19]]

 [[15 28 26]
  [ 8 16 15]
  [24 26 26]
  ...
  [17 19 19]
  [17 19 19]
  [17 19 19]]

 ...

D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0395.jpg
[[[44 84 82]
  [31 65 64]
  [ 7 31 29]
  ...
  [19 19 19]
  [19 19 19]
  [19 19 19]]

 [[ 0 24 23]
  [ 0 25 24]
  [ 0 18 16]
  ...
  [19 19 19]
  [19 19 19]
  [19 19 19]]

 [[ 2 24 22]
  [ 5 23 22]
  [ 9 21 21]
  ...
  [19 19 19]
  [19 19 19]
  [19 19 19]]

 ...

 [[19 21 21]
  [19 21 21]
  [19 21 21]
  ...
  [19 21 21]
  [19 21 21]
  [19 21 21]]

 [[19 21 21]
  [19 21 21]
  [19 21 21]
  ...
  [19 21 21]
  [19 21 21]
  [19 21 21]]

 [[19 21 21]
  [19 21 21]
  [19 21 21]
  ...
  [19 21 21]
  [19 21 21]
  [19 21 21]]]
D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0396.jpg
[[[ 33  86  89]
  [ 68 111 114]
  [  4  27  29]
  ...
  [ 19  19  19]
  [ 19  19  19]
  [ 19  19  19]]

 [[  0  16  21]
  [  0  33  36]
  [  0  16  19]
  ...
  [ 19  19  19]
  [ 19  19  19]
  [ 19  19  19]]

 [[  0  17  23]
  [  0  18  21]
  [ 14  23  26]
  ...


D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0412.jpg
[[[ 33  72 134]
  [ 19  51 100]
  [  7  21  49]
  ...
  [ 17  19  19]
  [ 17  19  19]
  [ 17  19  19]]

 [[  0  11  56]
  [  0  10  46]
  [  0  10  30]
  ...
  [ 17  19  19]
  [ 17  19  19]
  [ 17  19  19]]

 [[  1  18  31]
  [  4  16  26]
  [ 16  19  27]
  ...
  [ 17  19  19]
  [ 17  19  19]
  [ 17  19  19]]

 ...

 [[ 19  21  21]
  [ 19  21  21]
  [ 19  21  21]
  ...
  [ 19  21  22]
  [ 19  21  22]
  [ 19  21  22]]

 [[ 19  21  21]
  [ 19  21  21]
  [ 19  21  21]
  ...
  [ 19  21  22]
  [ 19  21  22]
  [ 19  21  22]]

 [[ 19  21  21]
  [ 19  21  21]
  [ 19  21  21]
  ...
  [ 19  21  22]
  [ 19  21  22]
  [ 19  21  22]]]
D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0413.jpg
[[[ 30  60 131]
  [ 47  73 127]
  [  0  17  35]
  ...
  [ 15  20  19]
  [ 15  20  19]
  [ 15  20  19]]

 [[  0   5  63]
  [  0   7  49]
  [  0  13  26]
  

D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0425.jpg
[[[ 29  66 150]
  [ 18  47 116]
  [  6  19  57]
  ...
  [ 19  19  19]
  [ 19  19  19]
  [ 19  19  19]]

 [[  0   0  65]
  [  0   6  58]
  [  4  12  41]
  ...
  [ 19  19  19]
  [ 19  19  19]
  [ 19  19  19]]

 [[  0  17  44]
  [  5  16  36]
  [ 17  20  25]
  ...
  [ 19  19  19]
  [ 19  19  19]
  [ 19  19  19]]

 ...

 [[ 19  21  21]
  [ 19  21  21]
  [ 19  21  21]
  ...
  [ 19  21  21]
  [ 19  21  21]
  [ 19  21  21]]

 [[ 19  21  21]
  [ 19  21  21]
  [ 19  21  21]
  ...
  [ 19  21  21]
  [ 19  21  21]
  [ 19  21  21]]

 [[ 19  21  21]
  [ 19  21  21]
  [ 19  21  21]
  ...
  [ 19  21  21]
  [ 19  21  21]
  [ 19  21  21]]]
D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0426.jpg
[[[ 37  71 147]
  [  0  24  81]
  [  0  15  36]
  ...
  [ 19  19  19]
  [ 19  19  19]
  [ 19  19  19]]

 [[  0   6  63]
  [  0  10  52]
  [  6  19  35]
  

D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0440.jpg
[[[ 23  76 173]
  [  0  28 101]
  [  0  12  39]
  ...
  [ 17  19  19]
  [ 17  19  19]
  [ 17  19  19]]

 [[  0   5  83]
  [  0   3  62]
  [  1  15  34]
  ...
  [ 17  19  19]
  [ 17  19  19]
  [ 17  19  19]]

 [[  0   8  44]
  [  2  15  41]
  [ 18  20  30]
  ...
  [ 17  19  19]
  [ 17  19  19]
  [ 17  19  19]]

 ...

 [[ 19  21  21]
  [ 19  21  21]
  [ 19  21  21]
  ...
  [ 19  21  22]
  [ 19  21  22]
  [ 19  21  22]]

 [[ 19  21  21]
  [ 19  21  21]
  [ 19  21  21]
  ...
  [ 19  21  22]
  [ 19  21  22]
  [ 19  21  22]]

 [[ 19  21  21]
  [ 19  21  21]
  [ 19  21  21]
  ...
  [ 19  21  22]
  [ 19  21  22]
  [ 19  21  22]]]
D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0441.jpg
[[[ 44  74 193]
  [ 73 100 186]
  [  0  13  36]
  ...
  [ 19  19  19]
  [ 19  19  19]
  [ 19  19  19]]

 [[  0   0  82]
  [  0   6  72]
  [  0  13  31]
  

D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0457.jpg
[[[ 31  47 213]
  [ 10  22 148]
  [  3   6  57]
  ...
  [ 17  19  19]
  [ 17  19  19]
  [ 17  19  19]]

 [[  0   0 105]
  [  0   0  89]
  [  8   8  48]
  ...
  [ 17  19  19]
  [ 17  19  19]
  [ 17  19  19]]

 [[  0   6  46]
  [  6  14  44]
  [ 17  17  33]
  ...
  [ 17  19  19]
  [ 17  19  19]
  [ 17  19  19]]

 ...

 [[ 19  21  22]
  [ 19  21  22]
  [ 19  21  22]
  ...
  [ 19  21  22]
  [ 19  21  22]
  [ 19  21  22]]

 [[ 19  21  22]
  [ 19  21  22]
  [ 19  21  22]
  ...
  [ 19  21  22]
  [ 19  21  22]
  [ 19  21  22]]

 [[ 19  21  22]
  [ 19  21  22]
  [ 19  21  22]
  ...
  [ 19  21  22]
  [ 19  21  22]
  [ 19  21  22]]]
D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0458.jpg
[[[ 14  29 222]
  [  0   6 152]
  [  0   5  53]
  ...
  [ 17  19  19]
  [ 17  19  19]
  [ 17  19  19]]

 [[  0   0 127]
  [  0   0  93]
  [  0   2  39]
  

D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0472.jpg
[[[23 37  0]
  [51 62 30]
  [21 26 11]
  ...
  [19 19 19]
  [19 19 19]
  [19 19 19]]

 [[21 32  0]
  [28 37 10]
  [21 25 13]
  ...
  [19 19 19]
  [19 19 19]
  [19 19 19]]

 [[19 27  4]
  [13 19  2]
  [21 23 17]
  ...
  [19 19 19]
  [19 19 19]
  [19 19 19]]

 ...

 [[19 21 22]
  [19 21 22]
  [19 21 22]
  ...
  [20 22 22]
  [20 22 22]
  [20 22 22]]

 [[19 21 22]
  [19 21 22]
  [19 21 22]
  ...
  [20 22 22]
  [20 22 22]
  [20 22 22]]

 [[19 21 22]
  [19 21 22]
  [19 21 22]
  ...
  [20 22 22]
  [20 22 22]
  [20 22 22]]]
D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0473.jpg
[[[27 42 14]
  [38 51 27]
  [21 28 13]
  ...
  [19 19 19]
  [19 19 19]
  [19 19 19]]

 [[16 29  5]
  [24 35 15]
  [14 21  8]
  ...
  [19 19 19]
  [19 19 19]
  [19 19 19]]

 [[16 23  8]
  [20 27 14]
  [15 19 13]
  ...
  [19 19 19]
  [19 19 19]
  [19 19 19]]

 ...

D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0495.jpg
[[[17 51 45]
  [11 36 32]
  [10 21 19]
  ...
  [17 19 19]
  [17 19 19]
  [17 19 19]]

 [[ 0 23 18]
  [ 0 23 19]
  [13 21 20]
  ...
  [17 19 19]
  [17 19 19]
  [17 19 19]]

 [[ 0 22 18]
  [ 5 22 19]
  [16 22 21]
  ...
  [17 19 19]
  [17 19 19]
  [17 19 19]]

 ...

 [[19 21 22]
  [19 21 22]
  [19 21 22]
  ...
  [19 21 22]
  [19 21 22]
  [19 21 22]]

 [[19 21 22]
  [19 21 22]
  [19 21 22]
  ...
  [19 21 22]
  [19 21 22]
  [19 21 22]]

 [[19 21 22]
  [19 21 22]
  [19 21 22]
  ...
  [19 21 22]
  [19 21 22]
  [19 21 22]]]
D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0496.jpg
[[[ 28  47  44]
  [102 116 114]
  [ 14  22  21]
  ...
  [ 17  19  19]
  [ 17  19  19]
  [ 17  19  19]]

 [[  6  23  20]
  [  9  23  21]
  [ 13  21  20]
  ...
  [ 17  19  19]
  [ 17  19  19]
  [ 17  19  19]]

 [[ 11  25  23]
  [  8  21  19]
  [ 14  20  19]
  ...


D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0511.jpg
[[[ 38  56  73]
  [101 117 133]
  [ 13  23  33]
  ...
  [ 17  19  19]
  [ 17  19  19]
  [ 17  19  19]]

 [[  0  14  30]
  [  0  13  27]
  [  6  15  24]
  ...
  [ 17  19  19]
  [ 17  19  19]
  [ 17  19  19]]

 [[  6  15  28]
  [  4  13  23]
  [ 11  17  24]
  ...
  [ 17  19  19]
  [ 17  19  19]
  [ 17  19  19]]

 ...

 [[ 18  20  21]
  [ 18  20  21]
  [ 18  20  21]
  ...
  [ 18  20  21]
  [ 18  20  21]
  [ 18  20  21]]

 [[ 18  20  21]
  [ 18  20  21]
  [ 18  20  21]
  ...
  [ 18  20  21]
  [ 18  20  21]
  [ 18  20  21]]

 [[ 18  20  21]
  [ 18  20  21]
  [ 18  20  21]
  ...
  [ 18  20  21]
  [ 18  20  21]
  [ 18  20  21]]]
D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0512.jpg
[[[ 31  51  76]
  [140 155 174]
  [  9  15  26]
  ...
  [ 17  19  19]
  [ 17  19  19]
  [ 17  19  19]]

 [[  0  13  34]
  [  9  24  40]
  [ 11  16  25]
  

D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0529.jpg
[[[ 15  41 111]
  [ 33  54 105]
  [ 11  18  35]
  ...
  [ 17  19  19]
  [ 17  19  19]
  [ 17  19  19]]

 [[  0   6  59]
  [  0  12  52]
  [  9  13  24]
  ...
  [ 17  19  19]
  [ 17  19  19]
  [ 17  19  19]]

 [[ 16  15  35]
  [ 12  12  26]
  [ 23  22  24]
  ...
  [ 17  19  19]
  [ 17  19  19]
  [ 17  19  19]]

 ...

 [[ 18  20  21]
  [ 18  20  21]
  [ 18  20  21]
  ...
  [ 18  20  21]
  [ 18  20  21]
  [ 18  20  21]]

 [[ 18  20  21]
  [ 18  20  21]
  [ 18  20  21]
  ...
  [ 18  20  21]
  [ 18  20  21]
  [ 18  20  21]]

 [[ 18  20  21]
  [ 18  20  21]
  [ 18  20  21]
  ...
  [ 18  20  21]
  [ 18  20  21]
  [ 18  20  21]]]
D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0530.jpg
[[[ 20  41 109]
  [ 65  81 134]
  [  5   9  37]
  ...
  [ 17  19  19]
  [ 17  19  19]
  [ 17  19  19]]

 [[  0   4  55]
  [  1  13  53]
  [  4   8  26]
  

D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0542.jpg
[[[ 35  53 124]
  [ 73  88 144]
  [  8  20  44]
  ...
  [ 17  19  19]
  [ 17  19  19]
  [ 17  19  19]]

 [[  0   5  61]
  [  2  15  59]
  [  0   6  24]
  ...
  [ 17  19  19]
  [ 17  19  19]
  [ 17  19  19]]

 [[  1  15  38]
  [  1  13  31]
  [ 13  19  26]
  ...
  [ 17  19  19]
  [ 17  19  19]
  [ 17  19  19]]

 ...

 [[ 18  20  21]
  [ 18  20  21]
  [ 18  20  21]
  ...
  [ 18  20  21]
  [ 18  20  21]
  [ 18  20  21]]

 [[ 18  20  21]
  [ 18  20  21]
  [ 18  20  21]
  ...
  [ 18  20  21]
  [ 18  20  21]
  [ 18  20  21]]

 [[ 18  20  21]
  [ 18  20  21]
  [ 18  20  21]
  ...
  [ 18  20  21]
  [ 18  20  21]
  [ 18  20  21]]]
D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0543.jpg
[[[ 40  55 148]
  [ 57  72 141]
  [  0  11  37]
  ...
  [ 19  19  19]
  [ 19  19  19]
  [ 19  19  19]]

 [[  0   0  70]
  [  0   1  55]
  [  4  16  34]
  

[[[ 26  51 167]
  [ 90 109 200]
  [  7  12  51]
  ...
  [ 17  17  17]
  [ 17  17  17]
  [ 17  17  17]]

 [[  0   0  86]
  [  0  10  79]
  [  1   5  34]
  ...
  [ 17  17  17]
  [ 17  17  17]
  [ 17  17  17]]

 [[  0   6  44]
  [  0   8  37]
  [ 20  19  28]
  ...
  [ 17  17  17]
  [ 17  17  17]
  [ 17  17  17]]

 ...

 [[ 18  20  21]
  [ 18  20  21]
  [ 18  20  21]
  ...
  [ 18  20  21]
  [ 18  20  21]
  [ 18  20  21]]

 [[ 18  20  21]
  [ 18  20  21]
  [ 18  20  21]
  ...
  [ 18  20  21]
  [ 18  20  21]
  [ 18  20  21]]

 [[ 18  20  21]
  [ 18  20  21]
  [ 18  20  21]
  ...
  [ 18  20  21]
  [ 18  20  21]
  [ 18  20  21]]]
D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0560.jpg
[[[ 24  53 168]
  [ 35  59 149]
  [  0   7  50]
  ...
  [ 19  19  19]
  [ 19  19  19]
  [ 19  19  19]]

 [[  0   0  84]
  [  0   5  76]
  [  0   5  38]
  ...
  [ 19  19  19]
  [ 19  19  19]
  [ 19  19  19]]

 [[  0  11  54]
  [  0   7  41]
  [ 16  20  31]
  ...


D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0576.jpg
[[[ 33  37 192]
  [  0   0 118]
  [  0   5  46]
  ...
  [ 17  17  17]
  [ 17  17  17]
  [ 17  17  17]]

 [[  0   0 110]
  [  0   0  82]
  [  6  11  42]
  ...
  [ 17  17  17]
  [ 17  17  17]
  [ 17  17  17]]

 [[  0   4  51]
  [  4  10  45]
  [ 10  13  27]
  ...
  [ 17  17  17]
  [ 17  17  17]
  [ 17  17  17]]

 ...

 [[ 18  20  21]
  [ 18  20  21]
  [ 18  20  21]
  ...
  [ 19  21  22]
  [ 19  21  22]
  [ 19  21  22]]

 [[ 18  20  21]
  [ 18  20  21]
  [ 18  20  21]
  ...
  [ 19  21  22]
  [ 19  21  22]
  [ 19  21  22]]

 [[ 18  20  21]
  [ 18  20  21]
  [ 18  20  21]
  ...
  [ 19  21  22]
  [ 19  21  22]
  [ 19  21  22]]]
D:/Data_collection/car_data/car_load_data/topcar_except/night/192708 (5-20-2020 4-18-54 PM)\192708 0577.jpg
[[[ 40  39 189]
  [ 21  22 136]
  [  6  15  53]
  ...
  [ 15  17  17]
  [ 15  17  17]
  [ 15  17  17]]

 [[  0   0  94]
  [  0   0  78]
  [  3   9  38]
  

In [18]:
img =cv2.imread(file_path)
adjust_gamma(img, 2.0)

array([[[ 55, 121,  74],
        [107, 146, 115],
        [ 57, 100,  59],
        ...,
        [ 63,  61,  65],
        [ 63,  61,  65],
        [ 63,  61,  65]],

       [[  0,  91,  39],
        [ 73, 114,  81],
        [ 39,  79,  39],
        ...,
        [ 63,  61,  65],
        [ 63,  61,  65],
        [ 63,  61,  65]],

       [[  0,  59,  27],
        [ 27,  63,  45],
        [ 42,  57,  45],
        ...,
        [ 63,  61,  65],
        [ 63,  61,  65],
        [ 63,  61,  65]],

       ...,

       [[ 65,  69,  71],
        [ 65,  69,  71],
        [ 65,  69,  71],
        ...,
        [ 85, 118, 134],
        [ 85, 118, 134],
        [ 85, 118, 134]],

       [[ 65,  69,  71],
        [ 65,  69,  71],
        [ 65,  69,  71],
        ...,
        [ 85, 118, 134],
        [ 85, 118, 134],
        [ 85, 118, 134]],

       [[ 65,  69,  71],
        [ 65,  69,  71],
        [ 65,  69,  71],
        ...,
        [ 85, 118, 134],
        [ 85, 118, 134],
        [ 85, 118, 134]]

## image_choice_delete