# Numpy(수치해석용 패키지)

In [25]:
import numpy as np

### 배열 생성

In [9]:
data = np.array([1,2,3,4])

In [10]:
data, type(data)

(array([1, 2, 3, 4]), numpy.ndarray)

In [11]:
data_2 = np.zeros(5)
data_2

array([0., 0., 0., 0., 0.])

In [12]:
data_3 = np.ones([3,5])
data_3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [13]:
data_4 = np.arange(0,10,1)   #기억 for i in "range()"
data_4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
data_5 = np.linspace(1,10,5)   #(시작, 끝(포함), 개수)
data_5

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [21]:
data_log = np.logspace(1,10,5)
data_log

array([1.00000000e+01, 1.77827941e+03, 3.16227766e+05, 5.62341325e+07,
       1.00000000e+10])

In [45]:
data_6 = np.random.randint(1,10,size=(2,10))
data_6

array([[2, 1, 6, 1, 9, 1, 8, 5, 5, 2],
       [8, 9, 5, 7, 4, 7, 4, 9, 3, 1]])

- data_6과 동일한 size의 0 array를 만들고 싶다면?

In [22]:
data_zero = np.zeros_like(data_6)
data_zero

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [24]:
data_one = np.ones_like(data_6)
data_one

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

### 배열 파악 

In [26]:
data_one.ndim   #배열의 차원

2

In [27]:
data_one.shape   #배열의 shape

(2, 10)

In [28]:
data_one.dtype   #배열의 데이터의 type

dtype('int32')

In [33]:
#리스트와 비교
data_list = [1, 2.0, 'hello']

data_array = np.array([1,2.0])
data_array

array([1., 2.])

In [34]:
data_array.dtype

dtype('float64')

In [35]:
data_array[0]

1.0

In [39]:
data_array2 = np.array([1,2,3])

data_array2.astype('f')  #배열의 데이터의 형변환

array([1., 2., 3.], dtype=float32)

In [44]:
data_array2.astype('O')  #주의 문자열 : 'O(알파벳)'

array([1, 2, 3], dtype=object)

### Numpy의 강점 

- 1개의 데이터 : vector = 1차원 배열
- 여러개의 데이터 : matrix = 2차원 배열

1. 벡터와 연산이 가능하다.
2. 변환이 쉽다.
3. 조건식으로 데이터 지정하기가 쉽다. 
4. 계산이 빠르다.

In [47]:
#리스트와 비교
a = [1,2,3]
c = a*3   #덧셈은 불가능
c

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [50]:
x = np.array(a)   
y ,z = x + 3, x*3   #각각의 원소에 덧셈, 곱셉.
y, z

(array([4, 5, 6]), array([3, 6, 9]))

In [51]:
x + y

array([5, 7, 9])

In [52]:
x*y

array([ 4, 10, 18])

In [54]:
data1 = np.array([1,2,3,4])
data2 = np.array([4,1,0,0])

data1+data2, data1*data2

(array([5, 3, 3, 4]), array([4, 2, 0, 0]))

In [56]:
data1@data2  #행렬의 곱

6

In [59]:
data3 = np.array([[1,2],[3,0]])
data4 = np.array([[1,0,1,0],[2,0,1,1]])

data3@data4   #data3.dot(data4) = np.dot(data3, data4)

array([[5, 0, 3, 2],
       [3, 0, 3, 0]])

In [60]:
data4 = np.array([[1,0,1,0],[2,0,1,1]])
data4

array([[1, 0, 1, 0],
       [2, 0, 1, 1]])

- data4를 전치키시고 싶다면? (대각선 회전)

In [62]:
data4.T

array([[1, 2],
       [0, 0],
       [1, 1],
       [0, 1]])

In [64]:
data7 = np.arange(10)  # = for i in "range"를 기억하자
data7

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

- 전치가 아니라 내가 원하는 shape으로 바꾸고 싶다면?

In [66]:
data7.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

- data7에서 짝수만 뽑아내고 싶다면?

In [68]:
data7[data7%2 == 0]   #조건식으로 지정 가능

array([0, 2, 4, 6, 8])